@EasyNetQ.Publish.API_HostAddress = https://localhost:7116

GET {{EasyNetQ.Publish.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{EasyNetQ.Publish.API_HostAddress}}/api/publish
Content-Type: application/json

{
  "Id": 1,
  "Name": "João"
}

###

POST {{EasyNetQ.Publish.API_HostAddress}}/api/publish
Content-Type: application/json

{
  //PublishModel
}

###
